package org.openchemlib.wasm.api;

import org.teavm.classlib.ResourceSupplier;
import org.teavm.classlib.ResourceSupplierContext;

/**
 * Generated by scripts/copy-openchemlib.mjs — do not edit. Tells TeaVM which
 * classpath resources to bundle into the wasm, so OpenChemLib's parameter tables
 * are available at runtime with no registration step.
 */
public class OclResourceSupplier implements ResourceSupplier {
  @Override
  public String[] supplyResources(ResourceSupplierContext context) {
    return new String[] {
      "resources/cod/bondLengthData.txt",
      "resources/cod/torsionAngle.txt",
      "resources/cod/torsionFrequency.txt",
      "resources/cod/torsionID.txt",
      "resources/cod/torsionRange.txt",
      "resources/forcefield/mmff94/94s/outofplane.csv",
      "resources/forcefield/mmff94/94s/torsionPlus.csv",
      "resources/forcefield/mmff94/94s/torsion.csv",
      "resources/forcefield/mmff94/angle.csv",
      "resources/forcefield/mmff94/atom.csv",
      "resources/forcefield/mmff94/bci.csv",
      "resources/forcefield/mmff94/bndk.csv",
      "resources/forcefield/mmff94/bond.csv",
      "resources/forcefield/mmff94/covrad.csv",
      "resources/forcefield/mmff94/def.csv",
      "resources/forcefield/mmff94/dfsb.csv",
      "resources/forcefield/mmff94/herschbachlaurie.csv",
      "resources/forcefield/mmff94/outofplane.csv",
      "resources/forcefield/mmff94/pbci.csv",
      "resources/forcefield/mmff94/stbn.csv",
      "resources/forcefield/mmff94/torsion.csv",
      "resources/forcefield/mmff94/vanderwaals.csv",
      "resources/druglikenessNoIndex.txt",
      "resources/toxpredictor/i1.txt",
      "resources/toxpredictor/i2.txt",
      "resources/toxpredictor/i3.txt",
      "resources/toxpredictor/m1.txt",
      "resources/toxpredictor/m2.txt",
      "resources/toxpredictor/m3.txt",
      "resources/toxpredictor/r1.txt",
      "resources/toxpredictor/r2.txt",
      "resources/toxpredictor/r3.txt",
      "resources/toxpredictor/t1.txt",
      "resources/toxpredictor/t2.txt",
      "resources/toxpredictor/t3.txt",
    };
  }
}
